defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

# domain: dmc
# task_names: [acrobot_swingup, finger_turn_hard, hopper_stand, walker_run, quadruped_walk, humanoid_stand, dog_walk]
#task_names: [quadruped_walk, walker_walk, walker_stand, cheetah_run, humanoid_walk, hopper_stand]
#task_names: [quadruped_run, walker_run, walker_walk, hopper_hop]
pcgrad: true
#multisteps: [1,1,1,3]
#multisteps: [3, 1, 3, 1, 1, 3]
#multisteps: [3, 3, 3, 1, 1, 3, 1]
# multisteps: [3,3,3,3,3,3,3]

domain: metaworld
task_names: ['button_press', 'coffee_pull', 'stick_pull', 'drawer_close', 'handle_press', 'pick_place', 'push_wall', 'reach_wall', 'peg_unplug_side', 'door_lock']
multisteps: [3,3,3,3,3,3,3,3,3,3]

taco: true
r3m: false
num_train_steps: 100000
bn: false
trunk: true
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50
exp_name: default
spr: false
curl: true
target: taco_representation_mt.TACORepresentation
  
agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_shapes: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  multisteps: ${multisteps}
  spr: ${spr}
  curl: ${curl}
  trunk: ${trunk}
  r3m: ${r3m}
  pcgrad: ${pcgrad}
  taco: ${taco}
  bn: ${bn}


hydra:
  run:
    dir: ./exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

