
defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

domain: dmc
use_augmentation: true
freeze_encoder: false
r3m: false
act_quantizer_dir: none
eval_freq: 50000
offline_data_dir: ???
encoder_dir: none
num_train_steps: 1000000
pcgrad: true
inverse: true
n_code: 40
num_beams: 50

#mpc hyperparameters
horizon: 10
num_samples: 512
iterations: 6
num_elites: 64
momentum: 0.1
temperature: 0.5

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 0
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr: 5e-5
encoder_lr: 5e-5
feature_dim: 50
exp_name: default
inv: false
reward: true
temporal: false
multistep: 1
lars: false
drqv2: false
spr: false
curl: true
target: latent_dynamics.STLatentDynamics
  
agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  use_tb: ${use_tb}
  freeze_encoder: ${freeze_encoder}
  use_augmentation: ${use_augmentation}
  horizon: ${horizon}
  num_samples: ${num_samples}
  iterations: ${iterations}
  num_elites: ${num_elites} 
  momentum: ${momentum}
  temperature: ${temperature}
  discount: ${discount}
  n_code: ${n_code}
  inverse: ${inverse}
  num_beams: ${num_beams}
  

hydra:
  run:
    dir: ./dynamics_exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

