defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

#task_names: ['assembly', 'basketball'] # for testing
data_storage_dir: /mount_point/offline-data-libero
task_data_dir_suffix: _expert500
results_dir: /mount_point/taa_results
downstream_task_name: none
downstream_task_suite: libero_10
tokenized_data_dir: tmp/tokenized
log_root_dir: exp_local


split: 1
max_traj_per_task: 100

alpha: 3
load_snapshot: true
stage: 1
pcgrad: false
n_code: 200
vocab_size: 200
eval: true
num_envs: 20
num_eval_episodes: 40
eval_max_steps: 600
eval_freq: 5000
port: 12235
obs_dependent: false
reinit_metapolicy: true
min_frequency: 5
max_token_length: 20
non_bpe: false


exp_bc_name: default
cross_entropy: false
bc: false
num_train_steps: 100100
trunk: true
# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000000
replay_buffer_num_workers: 4
nstep: 3 ### set nstep=5 during stage 3
nstep_history: 10
batch_size: 128
# misc
seed: 1
device: cuda
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 100
hidden_dim: 1024
exp_name: default
target: taco_representation_mt_transformer.TACORepresentation
action_dim: 7
img_res: [128, 128]
decoder_type: gmm
positional_embedding: absolute

agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_dim: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  hidden_dim: ${hidden_dim}
  feature_dim: ${feature_dim}
  trunk: ${trunk}
  pcgrad: ${pcgrad}
  n_code: ${n_code}
  vocab_size: ${vocab_size}
  nstep: ${nstep}
  nstep_history: ${nstep_history}
  obs_dependent: ${obs_dependent}
  alpha: ${alpha}
  decoder_type: ${decoder_type}
  positional_embedding: ${positional_embedding}


hydra:
  run:
    dir: ./${log_root_dir}/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
