
defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

domain: dmc
<<<<<<< HEAD
visual_only: true
=======
use_augmentation: false
>>>>>>> 68f63aec32770e38f046019ca5701ddf0c55b59c
freeze_encoder: false
r3m: false
act_quantizer_dir: none
eval_freq: 10000
offline_data_dir: ???
encoder_dir: none
<<<<<<< HEAD
num_train_steps: 100000
use_augmentation: false
=======
num_train_steps: 50000
pcgrad: true
bn: false
trunk: true
>>>>>>> 68f63aec32770e38f046019ca5701ddf0c55b59c

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 0
# eval
eval_every_frames: 10000
num_eval_episodes: 100
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
encoder_lr: 1e-4
feature_dim: 50
exp_name: default
inv: false
reward: true
temporal: false
multistep: 1
lars: false
drqv2: false
spr: false
curl: true
target: bc.BCAgent
mse: true
  
agent:
  _target_: ${target}
  state_dim: ???
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  encoder_lr: ${encoder_lr}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  use_tb: ${use_tb}
  r3m: ${r3m}
  freeze_encoder: ${freeze_encoder}
  use_augmentation: ${use_augmentation}
<<<<<<< HEAD
  visual_only: ${visual_only}
=======
  bn: ${bn}
  trunk: ${trunk}
  mse: ${mse}
>>>>>>> 68f63aec32770e38f046019ca5701ddf0c55b59c

hydra:
  run:
    dir: ./exp_results/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

