defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

task_name: 'bin-picking'
eval_freq: 5000
num_eval_episodes: 40
offline_data_dir: ???
tokenizer_dir: ???
multistep: 1

reinit_metapolicy: false
pcgrad: true
n_code: 200
vocab_size: 200

r3m: false
num_train_steps: 50000
trunk: true
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 100
hidden_dim: 1024
exp_name: default
spr: false
target: taco_representation_mt.TACORepresentation
  
agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_dim: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  hidden_dim: ${hidden_dim}
  feature_dim: ${feature_dim}
  spr: ${spr}
  trunk: ${trunk}
  r3m: ${r3m}
  pcgrad: ${pcgrad}
  n_code: ${n_code}
  nstep: ${nstep}


hydra:
  run:
    dir: ./exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

